version: '3.0'

services:
  nginx:
    image: nginx
    volumes:
      - ./config/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www
    container_name: ${DOCKER_PROJECT_NAME}-nginx
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - php-fpm
    networks:
      - internal

  php-fpm:
    image: yuriyyurinskiy/php:7.4-fpm
    volumes:
      - .:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal. remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    restart: always
    container_name: ${DOCKER_PROJECT_NAME}-php-fpm
    depends_on:
      - mysql
    networks:
      - internal

  php-cli:
    image: yuriyyurinskiy/php:7.4-cli
    volumes:
      - .:/var/www
    command: sleep 10000
    container_name: ${DOCKER_PROJECT_NAME}-php-cli

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    container_name: ${DOCKER_PROJECT_NAME}-mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${DOCKER_MYSQL_DATABASE}"
      - "MYSQL_USER=${DOCKER_MYSQL_USER}"
      - "MYSQL_PASSWORD=${DOCKER_MYSQL_PASSWORD}"

volumes:
  mysql:

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28